### ISSUE TITLE
Can't seem to find a way to set LogLevel

### ISSUE THREAD

**Issue by compscidr** [segmentio/analytics-kotlin#164]
The docs for (I'm assuming the none-kotlin version), mention there is a LogLevel that can be set when initilaizing the sdk: https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/#adding-debug-logging

I would like to disable logging - because when the phone is offline, the logs are being spammed because it cannot reach `api.segment.io`

Is there a way to do this that I am missing?

**Comment by wenxi-zeng** [comment]
hi @compscidr, in analytics-kotlin, you can customize your own flush policy to make segment not flush when the device is offline. please take a look at these samples: [UnmeteredFlushPolicy](https://github.com/segmentio/analytics-kotlin/blob/main/samples/kotlin-android-app/src/main/java/com/segment/analytics/next/UnmeteredFlushPolicy.kt) and other [policies](https://github.com/segmentio/analytics-kotlin/tree/main/core/src/main/java/com/segment/analytics/kotlin/core/platform/policies)

**Comment by compscidr** [comment]
Sure, but don't you think there should still be a way to control whether segment is logging or not? That was the original request here.

**Comment by wenxi-zeng** [comment]
so you mean the debug logs that segment prints to logcat? by default, it is disabled, but you can toggle it on/off through `Analytics.debugLogsEnabled` (see this [line](https://github.com/segmentio/analytics-kotlin/blob/main/core/src/main/java/com/segment/analytics/kotlin/core/Analytics.kt#L59)). also, such logs are not sent to `api.segment.io`. that's why I was assuming you were talking about disabling event flushing.
if you meant to disable segment completely to not track any events, we do have an internal ticket to track this feature request. but currently it's not available.

**Comment by compscidr** [comment]
I'm talking about logging to the android logcat logger - I'm not worried about the logs being sent to api.segment.io - more concerned with the debug logs, I'm trying to debug other things in my app but the logs are flooded with exceptions from segment, I would think with the `debugLogsEnabled` set to false, it wouldn't show these types of exceptions but it still seems to.

**Comment by compscidr** [comment]
For example this gets spammed continually:
```
2023-05-22 09:24:53.634 12947-12998 System.err              xyz.bumpapp.dev.debug                W  java.net.UnknownHostException: Unable to resolve host "api.segment.io": No address associated with hostname
2023-05-22 09:24:53.634 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
2023-05-22 09:24:53.634 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
2023-05-22 09:24:53.634 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
2023-05-22 09:24:53.634 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
2023-05-22 09:24:53.634 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.segment.analytics.kotlin.core.HTTPClientKt.createPostConnection(HTTPClient.kt:93)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.segment.analytics.kotlin.core.HTTPClient.upload(HTTPClient.kt:32)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at com.segment.analytics.kotlin.core.platform.EventPipeline$upload$1.invokeSuspend(EventPipeline.kt:129)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at java.lang.Thread.run(Thread.java:1012)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at libcore.io.Linux.android_getaddrinfo(Native Method)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
2023-05-22 09:24:53.635 12947-12998 System.err              xyz.bumpapp.dev.debug                W  	... 24 more
```

I'm sure, as you said if I configure the flush policy and everything such that it doesn't try to flush it will solve it - but I'd expect that if debuglogs are disabled it would also not show up.

**Comment by wenxi-zeng** [comment]
ah. I see. yeah. I do see a line that's print out the [stack trace](https://github.com/segmentio/analytics-kotlin/blob/main/core/src/main/java/com/segment/analytics/kotlin/core/platform/EventPipeline.kt#L189) disrespect the segment log settings. we will get it removed. thanks for reporting this. in the meanwhile, please try the flush policy to avoid run into this issue.
