### ISSUE TITLE
Crash: This isn't a hierarchical URI

### ISSUE THREAD

**Issue by niallkh** [segmentio/analytics-kotlin#167]
**Describe the bug**

```
Caused by java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
       at android.net.Uri.getQueryParameterNames(Uri.java:1616)
       at com.segment.analytics.kotlin.android.utilities.DeepLinkUtils.trackDeepLinkFrom(DeepLinkUtils.kt:24)
       at com.segment.analytics.kotlin.android.plugins.AndroidLifecyclePlugin.trackDeepLink(AndroidLifecyclePlugin.kt:218)
       at com.segment.analytics.kotlin.android.plugins.AndroidLifecyclePlugin.onActivityCreated(AndroidLifecyclePlugin.kt:96)
       at android.app.Application.dispatchActivityCreated(Application.java:367)
```
       

**To Reproduce**
1. Open app with not hierarchical uri deeplink 
2. Crash

**Platform (please complete the following information):**
 - Library Version in use: 1.10.6
 - Platform being tested: Android

**Comment by didiergarcia** [comment]
Hi @niallkh, thanks for reaching out. Yeah looks like we do crash in this instance. We'll get that fixed ASAP.

Curious, what's your use-case for non-hierarchical URIs? Like why do you use them? Do you see benefits? etc. 

Thanks!

**Comment by amal** [comment]
Actually, there are tons of use cases for non-hierarchical URIs. It can be anything that is just encoded in URI and handled by the app. E.g. references, API handles, blockchain addresses, requests, etc.
