### ISSUE TITLE
Having issues with minified builds 

### ISSUE THREAD

**Issue by joel-apollo** [segmentio/analytics-kotlin#20]
**Describe the bug**
I'm having quite a few issues running a minified build with this library. Used the Kotlinx.serialization rules, but still getting stacktraces like this:

```
kotlinx.serialization.SerializationException: Serializer for class 't' is not found.
    Mark the class as @Serializable or provide the serializer explicitly.
        at com.google.android.gms.measurement.internal.zzbh.kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(:1)
                                                            kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered
        at com.google.android.gms.measurement.internal.zzbn.kotlinx.serialization.SerializersKt__SerializersKt.serializer(:1)
                                                            kotlinx.serialization.SerializersKt.serializer
        at com.segment.analytics.kotlin.core.SegmentDestination.track(:2)
        at com.segment.analytics.kotlin.core.platform.DestinationPlugin.process(Unknown Source:36)
        at androidx.compose.ui.input.pointer.HitPathTracker.com.segment.analytics.kotlin.core.platform.Mediator.execute(:1)
                                                            com.segment.analytics.kotlin.core.platform.Timeline.applyPlugins
        at androidx.compose.ui.input.pointer.HitPathTracker.com.segment.analytics.kotlin.core.platform.Timeline.applyPlugins(Unknown Source:10)
        at com.segment.analytics.kotlin.core.Analytics$process$1.com.segment.analytics.kotlin.core.platform.Timeline.process(:3)
                                                                 invokeSuspend
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:6)
        at kotlinx.coroutines.DispatchedTask.run(Unknown Source:86)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

The rules I added for progaurd/R8 are
```
# kotlinx-serialization-json specific. Add this if you have java.lang.NoClassDefFoundError kotlinx.serialization.json.JsonObjectSerializer
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Customized
-keep,includedescriptorclasses class com.google.android.gms.measurement.**$$serializer { *; }
-keepclassmembers class com.google.android.gms.measurement.** {
    *** Companion;
}
-keepclasseswithmembers class com.google.android.gms.measurement.** {
    kotlinx.serialization.KSerializer serializer(...);
}

```  

**To Reproduce**
Use the library with a minified build

**Expected behavior**
App runs

**Screenshots**
n/a

**Platform (please complete the following information):**
 - Library Version in use: [e.g. 0.0.5]
 - Platform being tested: Android
 - Integrations in use: Firebase?
 
**Additional context**

**Comment by prayansh** [comment]
Hey! @joel-apollo thanks for bringing this up! Can your try adding this to your proguard rules
```
-keep,includedescriptorclasses class com.segment.analytics.kotlin.**$$serializer { *; } 
-keepclassmembers class com.segment.analytics.kotlin.** {
    *** Companion;
}
-keepclasseswithmembers class com.segment.analytics.kotlin.** {
    kotlinx.serialization.KSerializer serializer(...);
}
```

I will add this to our consumer proguard rules so that in the future you wont have to worry about them :)
