### ISSUE TITLE
Use of unsupported Base64 API in API < 26

### ISSUE THREAD

**Issue by joel-apollo** [segmentio/analytics-kotlin#22]
The Java Base64 encoder isn't supported in Android API/SDK versions < 26, but the minSDK of the project is version 16

https://github.com/segmentio/analytics-kotlin/blob/494e6e537bafbd982aef7b023b80e9c25152e4ec/core/src/main/java/com/segment/analytics/kotlin/core/HTTPClient.kt#L37

See https://developer.android.com/reference/java/util/Base64

Causes crashes like this:
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
       at com.segment.analytics.kotlin.core.HTTPClient.authorizationHeader(HTTPClient.java)
       at com.segment.analytics.kotlin.core.HTTPClientKt.createPostConnection(HTTPClientKt.java)
       at com.segment.analytics.kotlin.core.SegmentDestination.performFlush(SegmentDestination.java:3)
       at com.segment.analytics.kotlin.core.SegmentDestination$flush$$inlined$run$lambda$1.invokeSuspend(SegmentDestination.java:3)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:5)
```

**Comment by prayansh** [comment]
Hey @joel-apollo! we have shipped a fix for this. I will be making a release with the new changes sometime this week and will update this thread when done :)
