### ISSUE TITLE
Unhandled android.os.DeadSystemException in ConnectivityManager call

### ISSUE THREAD

**Issue by tadfisher** [segmentio/analytics-kotlin#55]
**Describe the bug**

`ConnectivityManager.getNetworkCapabilities` can throw if the app is being killed due to a device restart. This most likely isn't user-facing, but I am receiving stack traces via telemetry and it may be worth handling.

Stack trace:
```console
java.lang.RuntimeException: android.os.DeadSystemException
        at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1566)
        at com.segment.analytics.kotlin.android.plugins.AndroidContextPlugin.execute(AndroidContextPlugin.kt:13)
        at com.segment.analytics.kotlin.core.platform.Timeline.applyPlugins(Timeline.kt:18)
        at com.segment.analytics.kotlin.core.Analytics$process$1.invokeSuspend(Analytics.kt:7)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

**To Reproduce**
I haven't been able to reproduce locally, but I suspect the timing has to be just right to trigger this exception (e.g. the system ConnectivityManager service has to be shut down before Analytics makes this call).

**Expected behavior**
This exception could be handled so automated crash reporting doesn't track an error which likely isn't important for clients to fix.

**Platform (please complete the following information):**
- analytics-kotlin version: 1.3.0
- Platform: Android
- No client-side integrations; Amplitude Actions on server-side

**Comment by wenxi-zeng** [comment]
as per https://developer.android.com/reference/android/os/DeadSystemException

> The core Android system has died and is going through a runtime restart. All running apps will be promptly killed.

this exception is thrown by the OS, and is not attached to any sdk/app. but rather means when the system reboots, the app/sdk happens to be in the memory and doing activities that references to an object that is dead. 

from another perspective, that means the app actively occupies memory. it's maybe a memory leak in the app. it is advisable to profile the app to ensure no memory leaks. 

closing this issue out.
